let CLO = [[
    // [ "Course Code", "Course Name", "Semester", "CLO #", "CLO Statement", "Domain", "Taxonomy Level", "PLO #" ],
    ["ME4823", "Engineering Management", "8th", "CLO 1", "Explain the role that the operations management function plays in business and how the operations function can play a strategic role in improving the competitiveness of the organization.", "Cognitive", 2, "PLO 11"],
    ["ME4823", "Engineering Management", "8th", "CLO 2", "Explain how an organization can improve its processes and integrate its several functions through the best use of quality engineering.", "Cognitive", 2, "PLO 7"],
    ["ME4823", "Engineering Management", "8th", "CLO 3", "Apply important strategies like total quality management, Six-Sigma, and Benchmarking into organizations", "Cognitive", 3, "PLO 11"],
    ["ME1101", "Communication & Presentation Skills", "1st", "CLO 1", "Interpret words and sentences clearly and efficiently.", "Cognitive", 2, "PLO 10"],
    ["ME1101", "Communication & Presentation Skills", "1st", "CLO 2", "Demonstrate written and oral presentation skills by preparing presentation materials / assignments", "Cognitive", 3, "PLO 10"],
    ["ME1101", "Communication & Presentation Skills", "1st", "CLO 3", "Communicate effectively in both written and oral forms.", "Affective", 2, "PLO 10"],
    ["ME1111-T", "Electric Ciruits", "1st", "CLO 1", "Interpret the concepts of electric current and voltage, and their interaction in different electric circuit configurations.", "Cognitive", 2, "PLO 1"],
    ["ME1111-T", "Electric Ciruits", "1st", "CLO 2", "Apply the laws of electrical engineering to series, parallel, series-parallel and complex electric circuits.", "Cognitive", 3, "PLO 2"],
    ["ME1111-L", "Electric Ciruits", "1st", "CLO 1", "Construct given open ended lab project", "Psychomotor", 3, "PLO 3"],
    ["ME1111-L", "Electric Ciruits", "1st", "CLO 2", "Investigate the voltages and currents of a complete electronic circuit", "Cognitive", 4, "PLO 3"],
    ["ME1111-L", "Electric Ciruits", "1st", "CLO 3", "Communicate effectively in both written and oral forms.", "Affective", 2, "PLO 3"],
    ["ME1111-L", "Electric Ciruits", "1st", "CLO 4", "Write weekly lab reports", "Cognitive", 3, "PLO 9"],
    ["ME1111-L", "Electric Ciruits", "1st", "CLO 5", "Reproduce the Setup for weekly experiments and lab exams", "Psychomotor", 2, "PLO 9"],
    ["ME1111-L", "Electric Ciruits", "1st", "CLO 6", "Participate responsibly to complete a task", "Affective", 2, "PLO 9"],
    ["ME1109", "Engineering Drawing-I", "1st", "CLO 1", "Describe drawing principles for adequate representation of engineering drawing models.", "Cognitive", 2, "PLO 1"],
    ["ME1109", "Engineering Drawing-I", "1st", "CLO 2", "Apply principles of Engineering visualization and Projection theory for drafting purposes", "Cognitive", 3, "PLO 10"],
    ["ME1109", "Engineering Drawing-I", "1st", "CLO 3", "Inspect parts to make an effective assembly drawing in order to communicate effectively.", "Cognitive", 4, "PLO 10"],
    ["ME1104", "Engineering Mathematics-I", "1st", "CLO 1", "Classify the concept of limit / continuity / complex numbers / derivatives / the notions of definite and indefinite integration / techniques of integration", "Cognitive", 2, "PLO 1"],
    ["ME1104", "Engineering Mathematics-I", "1st", "CLO 2", "Apply the derivatives to find extrema, calculate lengths of curves / area of regions / volume of solids and show the convergence of the series.", "Cognitive", 3, "PLO 1"],
    ["ME1106", "Islamic Studies", "1st", "CLO 1", "Explain issues related to faith and religious life; fundamental human rights and relation with non-Muslims through discussion", "Cognitive", 2, "PLO 6"],
    ["ME1106", "Islamic Studies", "1st", "CLO 2", "Explain knowledge of Islamic civilization and moral values", "Cognitive", 2, "PLO 8"],
    ["ME1116", "Humnities", "1st", "CLO 1", "Classify architecture throughout time including designs and styles from periods. Analyze the relationship between religious beliefs and art in Ancient Egypt and Ancient Greece. Explain early Greek philosophers, the study of religion and philosophy and philosophy in the Middle Ages, Renaissance and the 20th Century.", "Cognitive", 2, "PLO 6"],
    ["ME1116", "Humnities", "1st", "CLO 2", "Appraise the different time periods and techniques of British and American literature. Demonstrate understanding of the effect of the Renaissance and Reformation in Europe on society, religion, and the arts. Examine art and identify distinguishing elements representative of various time periods and styles, including Greek, neoclassical and modern.", "Cognitive", 2, "PLO 8"],
    ["ME1203-T", "Engineering Physics", "1st", "CLO 1", "Define the basic terminologies related to applied physics.", "Cognitive", 1, "PLO 1"],
    ["ME1203-T", "Engineering Physics", "1st", "CLO 2", "Interpret concepts related to Mechanics; Fluids; Heat; Optics and Electromagnetism", "Cognitive", 2, "PLO 1"],
    ["ME1203-T", "Engineering Physics", "1st", "CLO 3", "Apply the key concepts of applied physics to solve engineering problems", "Cognitive", 3, "PLO 2"],
    ["ME1203-T", "Engineering Physics", "1st", "CLO 4", "Communicate effectively solution to assigned problem individually", "Affective", 2, "PLO 10"],
    ["ME1203-L", "Engineering Physics", "1st", "CLO 1", "Describe the basic principle of physics related to the apparatus and complete lab manual through experiment.", "Cognitive", 2, "PLO 9"],
    ["ME1203-L", "Engineering Physics", "1st", "CLO 2", "Setup the apparatus to find the experimental values that can be related with theoretical values using modern physics apparatus", "Psychomotor", 2, "PLO 9"],
    ["ME1203-L", "Engineering Physics", "1st", "CLO 3", "Communicate effectively by submitting lab reports on time", "Affective", 2, "PLO 9"],
    ["ME1203-L", "Engineering Physics", "1st", "CLO 4", "Constructs semester project as per provided guidelines.", "Psychomotor", 3, "PLO 3"],
    ["ME1203-L", "Engineering Physics", "1st", "CLO 5", "Prepares a project report to show the design and analysis involved in the project.", "Cognitive", 3, "PLO 3"],
    ["ME1203-L", "Engineering Physics", "1st", "CLO 6", "Respond to viva questions related to the project", "Affective", 2, "PLO 3"],
    ["ME1209", "Computer Programming", "1st", "CLO 1", "Interpret the basic concepts of procedural/structured programming", "Cognitive", 2, "PLO 1"],
    ["ME1209", "Computer Programming", "1st", "CLO 2", "Communicate effectively in oral form.", "Affective", 2, "PLO 1"],
    ["ME1209", "Computer Programming", "1st", "CLO 3", "Construct a Program i.e. a computer-based solution to a well-defined problem. This includes developing a general flow of logic, identifying the variables, conditional/iterative execution, fail conditions.", "Cognitive", 3, "PLO 5"],
    ["ME1209", "Computer Programming", "1st", "CLO 4", "Investigate appropriate solution for assigned task.", "Cognitive", 4, "PLO 12"],
    ["ME1209", "Computer Programming", "1st", "CLO 5", "Demonstrates the valuing attributes of a life-long learner for project selection and completion.", "Affective", 3, "PLO 12"],
    ["ME1201-T", "Electronic Devices and Circuits", "2nd", "CLO1", "Describe the construction and operating characteristics of Semiconductor diodes and bipolar junction transistors", "Cognitive", 2, "PLO1"],
    ["ME1201-T", "Electronic Devices and Circuits", "2nd", "CLO2", "Solve diode and BJT based circuits.", "Cognitive", 3, "PLO2"],
    ["ME1201-L", "Electronic Devices and Circuits", "2nd", "CLO1", "Demonstrate the results of a complete electronic circuit system (project).", "Cognitive", 3, "PLO3"],
    ["ME1201-L", "Electronic Devices and Circuits", "2nd", "CLO2", "Construct the hardware of the assigned project.", "Psychomotor", 3, "PLO3"],
    ["ME1201-L", "Electronic Devices and Circuits", "2nd", "CLO3", "Communicate effectively in both written and oral forms.", "Affective", 2, "PLO3"],
    ["ME1201-L", "Electronic Devices and Circuits", "2nd", "CLO4", "Write weekly lab reports", "Cognitive", 3, "PLO9"],
    ["ME1201-L", "Electronic Devices and Circuits", "2nd", "CLO5", "Reproduce the Setup for weekly experiments and lab exams", "Psychomotor", 2, "PLO9"],
    ["ME1201-L", "Electronic Devices and Circuits", "2nd", "CLO6", "Participate responsibly to complete a task", "Affective", 2, "PLO9"],
    ["ME1202", "Engineering Mathematics – II: Linear Algebra & Ordinary Differential Equations", "2nd", "CLO1", "Explain the basic concepts of linear algebra, matrix algebra and vector algebra, linear/nonlinear, homogeneous/ non-homogeneous ODE.", "Cognitive", 2, "PLO1"],
    ["ME1203", "Engineering Mathematics – II: Linear Algebra & Ordinary Differential Equations", "2nd", "CLO2", "Solve problems of ODEs, Linear Algebra and related topics.", "Cognitive", 3, "PLO2"],
    ["ME2306", "Pakistan Studies", "2nd", "CLO1", "Define the ideology of Pakistan with reference to the basic values of Islam and the socio-cultural milieu of Muslims in the sub-continent", "Cognitive", 1, "PLO6"],
    ["ME2306", "Pakistan Studies", "2nd", "CLO2", "Describe the early problems with particular emphasis on economic, geopolitical, refugee, state, and administrative problems, constitutional reforms of 1956, 1962, and 1973’s", "Cognitive", 2, "PLO6"],
    ["ME2306", "Pakistan Studies", "2nd", "CLO3", "Communicate the knowledge of topics relevant to geography, resources, and foreign policy of Pakistan which emphasizes progression and peaceful co-existence, and document their findings", "Affective", 2, "PLO6"],
    ["ME1204", "Engineering Statics", "2nd", "CLO1", "Interpret concepts of vectors and scalars, forces, moments and couples.", "Cognitive", 2, "PLO1"],
    ["ME1204", "Engineering Statics", "2nd", "CLO2", "Apply the learned concepts of forces, moments and couples to solve problems of equilibrium in 2-d and 3-d and problems of   friction", "Cognitive", 3, "PLO2"],
    ["ME1204", "Engineering Statics", "2nd", "CLO3", "Analyze structures such as plain trusses, frames and machines for reaction forces", "Cognitive", 4, "PLO2"],
    ["ME1207", "Engineering Workshop", "2nd", "CLO1", "Explain the working and classification of different tools and machines used in engineering workshop.", "Cognitive", 2, "PLO1"],
    ["ME1207", "Engineering Workshop", "2nd", "CLO2", "Construct parts/assemblies using carpentry, metal, foundry, welding, machine, robotics and electronics shops.", "Psychomotor", 3, "PLO1"],
    ["ME1207", "Engineering Workshop", "2nd", "CLO3", "Construct a wooden assembly to achieve the current theme of the workshop project and design a printed circuit boards (PCB) by a given schematics.", "Psychomotor", 3, "PLO4"],
    ["ME1207", "Engineering Workshop", "2nd", "CLO4", "Prepares a project report to show the design and analysis involved.", "Cognitive", 3, "PLO4"],
    ["ME1207", "Engineering Workshop", "2nd", "CLO5", "Participate responsibly to complete a task", "Affective", 2, "PLO9"],
    ["ME1208", "Materials and Manufacturing Processes", "2nd", "CLO1", "Interpret core concepts in materials science and manufacturing processes", "Cognitive", 2, "PLO1"],
    ["ME1208", "Materials and Manufacturing Processes", "2nd", "CLO2", "Illustrate the appropriate operation and its parameters for performing manufacturing processes", "Cognitive", 3, "PLO2"],
    ["ME1208", "Materials and Manufacturing Processes", "2nd", "CLO3", "Describe the environmental impacts of various materials and manufacturing processes.", "Cognitive", 2, "PLO7"],
    ["ME2312", "Data Structures & Object Oriented Programming", "2nd", "CLO1", "Define basic terminologies of programming such as loops, classes, and functions.", "Cognitive", 1, "PLO1"],
    ["ME2312", "Data Structures & Object Oriented Programming", "2nd", "CLO2", "Identify bugs and conclude the output of the program.", "Cognitive", 2, "PLO1"],
    ["ME2312", "Data Structures & Object Oriented Programming", "2nd", "CLO3", "Implement concept of object-oriented programming to construct a given program.", "Cognitive", 3, "PLO5"],
    ["ME2312", "Data Structures & Object Oriented Programming", "2nd", "CLO4", "Design an android app to achieve the proposed idea.", "Cognitive", 6, "PLO5"],
    ["ME2312", "Data Structures & Object Oriented Programming", "2nd", "CLO5", "Communicate effectively in both written and oral forms.", "Affective", 2, "PLO5"],
    ["ME2312", "Data Structures & Object Oriented Programming", "2nd", "CLO6", "Demonstrate ethical coding practices by avoiding plagiarism", "Affective", 3, "PLO8"],
    ["ME1110", "Teching Holuy Quran", "2nd", "CLO1", "Recite Holy Quran according to Tajweed principles, with translation of Ayat.", "Cognitive", 1, "PLO6"],
    ["ME1110", "Teching Holuy Quran", "2nd", "CLO2", "Define the principles of Ethics described in the Holy Quran", "Cognitive", 1, "PLO8"],
    ["ME1211", "Ideology and Constitution of Pakistan", "3rd", "CLO1", "Understand the significance of Pakistan's ideology, national identity, historical context, culture, civilization, and foreign policy on both the national and international fronts in today's globalized world.", "Cognitive", 1, "PLO6"],
    ["ME1211", "Ideology and Constitution of Pakistan", "3rd", "CLO2", "Describe the fundamental concerns, concepts, and regulations associated with the Constitution, the framework of government, and the political/administrative system in the nation.", "Cognitive", 2, "PLO6"],
    ["ME1211", "Ideology and Constitution of Pakistan", "3rd", "CLO3", "Communicate the knowledge of topics relevant to Pakistan's geography, resources, and foreign policy, which emphasizes progression and peaceful co-existence, and document their findings.", "Affective", 2, "PLO6"],
    ["ME2302-T", "Digital Logic Design", "3rd", "CLO1", "Describe:\ni. The use of Boolean Algebra and K-maps in designing efficient combinational and sequential logic circuits\nii. The operation of logic gates, flip flops, memory, sequential circuits and programmable logic", "Cognitive", 2, "PLO1"],
    ["ME2302-T", "Digital Logic Design", "3rd", "CLO2", "Solve combinational circuits, sequential circuits and medium-scale integrated circuits (Decoders, MUX, etc.)", "Cognitive", 3, "PLO2"],
    ["ME2302-T", "Digital Logic Design", "3rd", "CLO3", "Design combinational and sequential logic circuits using Boolean Algebra and K-maps", "Cognitive", 6, "PLO2"],
    ["ME2302-L", "Digital Logic Design", "3rd", "CLO1", "Demonstrate an electronic circuit system using different logic gates, combinational and sequential circuits.", "Cognitive", 3, "PLO3"],
    ["ME2302-L", "Digital Logic Design", "3rd", "CLO2", "Construct the hardware of the assigned project.", "Psychomotor", 3, "PLO3"],
    ["ME2302-L", "Digital Logic Design", "3rd", "CLO3", "Communicate effectively in both written and oral forms.", "Affective", 2, "PLO3"],
    ["ME2302-L", "Digital Logic Design", "3rd", "CLO4", "Write weekly lab reports", "Cognitive", 3, "PLO9"],
    ["ME2302-L", "Digital Logic Design", "3rd", "CLO5", "Reproduce the Setup for weekly experiments and lab exams", "Psychomotor", 2, "PLO9"],
    ["ME2302-L", "Digital Logic Design", "3rd", "CLO6", "Participate responsibly to complete a task", "Affective", 2, "PLO9"],
    ["ME2303", "Engineering Dynamics", "3rd", "CLO1", "Interpret concepts of the kinematics and kinetics of a single particle and simple particle systems, to simple problems of engineering interest.", "Cognitive", 2, "PLO1"],
    ["ME2303", "Engineering Dynamics", "3rd", "CLO2", "Apply the concepts of the kinematics of planar motion and kinetics of rigid bodies in planar motion.", "Cognitive", 3, "PLO2"],
    ["ME2304", "Engineering Mathematics – III: 3D Geometry & Vector Calculus", "3rd", "CLO1", "Classify problems involving the geometry of lines, curves, planes and surfaces in space.", "Cognitive", 2, "PLO1"],
    ["ME2304", "Engineering Mathematics – III: 3D Geometry & Vector Calculus", "3rd", "CLO2", "Solve vector functions using differentiation techniques and double / triple integrals by using appropriate theorems.", "Cognitive", 3, "PLo1"],
    ["ME2311", "Network Analysis", "3rd", "CLO1", "Describe the transient behavior of the first and second order passive circuits.", "Cognitive", 2, "PLO1"],
    ["ME2311", "Network Analysis", "3rd", "CLO2", "Apply sinusoidal-steady-state analysis of passive networks using the impedance method, including AC power analysis.", "Cognitive", 3, "PLO2"],
    ["ME2311", "Network Analysis", "3rd", "CLO3", "Use computer aid for passive networks.", "Cognitive", 3, "PLO5"],
    ["ME2309", "Eng. Drawing - II", "3rd", "CLO1", "Practice features of AUTOCAD in order to make orthographic, sectional and isometric views.", "Cognitive", 3, "PLO5"],
    ["ME2309", "Eng. Drawing - II", "3rd", "CLO2", "Prepare layouts that effectively communicate engineering drawing standards.", "Cognitive", 3, "PLO10"],
    ["ME2309", "Eng. Drawing - II", "3rd", "CLO3", "Inspect a 2D drawing in order to develop a 3D model or assembly and present as per standards.", "Cognitive", 5, "PLO10"],
    ["ME2308-T", "Fundamentals of Thermal Sciences", "3rd", "CLO1", "Describe the thermofluid properties, Distinguish different thermodynamic systems from a given scenario and explain the principles of heat transfer.", "Cognitive", 2, "PLO1"],
    ["ME2308-T", "Fundamentals of Thermal Sciences", "3rd", "CLO2", "Determine state characteristics for working fluids undergoing various processes, Solve the governing mathematical equations for conduction, convection and radiation heat transfer and Apply mass conservation, energy conservation and entropy balance relationships to thermodynamic problems related to closed and open systems.", "Cognitive", 3, "PLO2"],
    ["ME2308-T", "Fundamentals of Thermal Sciences", "3rd", "CLO3", "Analyze various thermodynamic cycles for reciprocating engines, power plants and refrigeration systems.", "Cognitive", 4, "PLO3"],
    ["ME2308-L", "Fundamentals of Thermal Sciences", "3rd", "CLO1", "Interpret the different parameters related to experiments and relate the interactions of those parameters with engineering principles.", "Cognitive", 2, "PLO9"],
    ["ME2308-L", "Fundamentals of Thermal Sciences", "3rd", "CLO2", "Reproduce the Setup for weekly experiments and lab exams", "Psychomotor", 2, "PLO9"],
    ["ME2308-L", "Fundamentals of Thermal Sciences", "3rd", "CLO3", "Participate responsibly to complete a task", "Affective", 2, "PLO9"],
    ["ME2308-L", "Fundamentals of Thermal Sciences", "3rd", "CLO4", "Construct hardware of open ended project for given constraints.", "Psychomotor", 3, "PLO3"],
    ["ME2308-L", "Fundamentals of Thermal Sciences", "3rd", "CLO5", "Propose solution to the assigned open ended project for given constraints.", "Cognitive", 6, "PLO3"],
    ["ME2308-L", "Fundamentals of Thermal Sciences", "3rd", "CLO6", "Demonstrate project management skills for project scheduling, execution and completion.", "Affective", 3, "PLO11"],
    ["ME2401-T", "Electronics Circuit Design", "4th", "CLO1", "Explain the construction and operating characteristics of Field Effect Transistors (FETs) and Op-Amps.", "Cognitive", 2, "PLO1"],
    ["ME2401-T", "Electronics Circuit Design", "4th", "CLO2", "Solve various FET, Op-Amp and BJT configurations.", "Cognitive", 3, "PLO2"],
    ["ME2401-L", "Electronics Circuit Design", "4th", "CLO1", "Design a complete electronic circuit system using a top-down approach which starts from system specifications.", "Cognitive", 6, "PLO4"],
    ["ME2401-L", "Electronics Circuit Design", "4th", "CLO2", "Construct the hardware of the assigned problem.", "Psychomotor", 3, "PLO4"],
    ["ME2401-L", "Electronics Circuit Design", "4th", "CLO3", "Discuss the working of the project and represent the effective use of time and resources in the form of report.", "Affective", 2, "PLO10"],
    ["ME2401-L", "Electronics Circuit Design", "4th", "CLO4", "Write weekly lab reports", "Cognitive", 3, "PLO9"],
    ["ME2401-L", "Electronics Circuit Design", "4th", "CLO5", "Reproduce the Setup for weekly experiments and lab exams", "Psychomotor", 2, "PLO9"],
    ["ME2401-L", "Electronics Circuit Design", "4th", "CLO6", "Participate responsibly to complete a task", "Affective", 2, "PLO9"],
    ["ME2401-L", "Electronics Circuit Design", "4th", "CLO7", "Demonstrate project management skills for project scheduling, execution and completion.", "Affective", 3, "PLO11"],
    ["ME2407-T", "Actuating Systems", "4th", "CLO1", "Explain principles of AC and DC motors and generators, and AC transformers, hydraulics and pneumatics actuators", "Cognitive", 2, "PLO1"],
    ["ME2407-T", "Actuating Systems", "4th", "CLO2", "Calculate parameters and credentials of AC and DC machines", "Cognitive", 3, "PLO2"],
    ["ME2407-L", "Actuating Systems", "4th", "CLO1", "Construct the hardware of the project using top-down approach.", "Psychomotor", 3, "PLO3"],
    ["ME2407-L", "Actuating Systems", "4th", "CLO2", "Investigate electromechanical systems by following the defined constraints.", "Cognitive", 4, "PLO3"],
    ["ME2407-L", "Actuating Systems", "4th", "CLO3", "Discuss the working of the project in the form of report and answers queries in form of viva.", "Affective", 2, "PLO3"],
    ["ME2407-L", "Actuating Systems", "4th", "CLO4", "Write weekly lab reports", "Cognitive", 3, "PLO9"],
    ["ME2407-L", "Actuating Systems", "4th", "CLO5", "Reproduce the Setup for weekly experiments and lab exams", "Psychomotor", 2, "PLO9"],
    ["ME2407-L", "Actuating Systems", "4th", "CLO6", "Participate responsibly to complete a task", "Affective", 2, "PLO9"],
    ["ME2403", "Engineering Mathematics – IV Transformation Techniques", "4th", "CLO1", "Explain the types of signals, systems and their time and frequency domain descriptions", "Cognitive", 2, "PLO1"],
    ["ME2403", "Engineering Mathematics – IV Transformation Techniques", "4th", "CLO2", "Calculate the time and frequency versions of signals and systems", "Cognitive", 3, "PLO2"],
    ["ME2403", "Engineering Mathematics – IV Transformation Techniques", "4th", "CLO3", "Analyze the discrete systems using relevant software.", "Cognitive", 4, "PLO5"],
    ["ME2406-T", "Strength of Materials", "4th", "CLO1", "Explain the concepts of stress, strain and mechanical properties of Engineering materials", "Cognitive", 2, "PLO1"],
    ["ME2406-T", "Strength of Materials", "4th", "CLO2", "Calculate the stresses and deflections in structures and machine components subjected to different modes of loading.", "Cognitive", 3, "PLO2"],
    ["ME2406-T", "Strength of Materials", "4th", "CLO3", "Analyze structures and machine components by applying principles of mechanics to achieve safe design.", "Cognitive", 4, "PLO2"],
    ["ME2406-L", "Strength of Materials", "4th", "CLO1", "Construct project: fabrication of test specimens with provided dimensions to imitate stress analysis", "Psychomotor", 3, "PLO4"],
    ["ME2406-L", "Strength of Materials", "4th", "CLO2", "Analyze trusses and measuring mechanical properties of structural materials.", "Cognitive", 4, "PLO4"],
    ["ME2406-L", "Strength of Materials", "4th", "CLO3", "Communicate effectively in both written and oral forms.", "Affective", 2, "PLO10"],
    ["ME2406-L", "Strength of Materials", "4th", "CLO4", "Reproduce the Setup for weekly experiments and lab exams", "Psychomotor", 2, "PLO2"],
    ["ME2406-L", "Strength of Materials", "4th", "CLO5", "Participate responsibly to complete a task", "Affective", 2, "PLO2"],
    ["ME2406-L", "Strength of Materials", "4th", "CLO6", "Write weekly lab reports", "Cognitive", 3, "PLO2"],
    ["ME2411-T", "Fluid Mechanics", "4th", "CLO1", "Explain the basic concepts of fluid mechanics based on analytical relations and Describe the fluid properties", "Cognitive", 2, "PLO1"],
    ["ME2411-T", "Fluid Mechanics", "4th", "CLO2", "Apply the basic concepts of fluid mechanics to solve problems related to hydrostatic fluids.", "Cognitive", 3, "PLO2"],
    ["ME2411-T", "Fluid Mechanics", "4th", "CLO3", "Solve fluid flow problems employing continuity, momentum and energy equations using Reynold Transport Theorem (RTT)", "Cognitive", 3, "PLO3"],
    ["ME2411-T", "Fluid Mechanics", "4th", "CLO4", "Differentiate between laminar and turbulent pipe flows, investigate losses in pipe systems and Analyze fluid flow problems using concepts of dimensional analysis and similitude.", "Cognitive", 4, "PLO3"],
    ["ME2411-L", "Fluid Mechanics", "4th", "CLO1", "Investigate assigned problem for given constraints through literature review.", "Cognitive", 4, "PLO4"],
    ["ME2411-L", "Fluid Mechanics", "4th", "CLO2", "Construct hardware of assigned problem.", "Psychomotor", 3, "PLO4"],
    ["ME2411-L", "Fluid Mechanics", "4th", "CLO3", "Write weekly lab reports", "Cognitive", 3, "PLO9"],
    ["ME2411-L", "Fluid Mechanics", "4th", "CLO4", "Reproduce the Setup for weekly experiments and lab exams", "Psychomotor", 2, "PLO9"],
    ["ME2411-L", "Fluid Mechanics", "4th", "CLO5", "Participate responsibly to complete a task", "Affective", 2, "PLO9"],
    ["ME3601", "Solid Modeling", "4th", "CLO1", "Apply engineering drawing standards and knowledge to develop 3D models and assemblies.", "Cognitive", 3, "PLO5"],
    ["ME3601", "Solid Modeling", "4th", "CLO2", "Propose solution for specific engineering problems and Create a CAD design for the proposed solution.", "Cognitive", 6, "PLO4"],
    ["ME3601", "Solid Modeling", "4th", "CLO3", "Demonstrates the valuing attributes of a life-long learner for project selection and completion.", "Affective", 3, "PLO12"],
    ["ME3601", "Solid Modeling", "4th", "CLO4", "Use tool box components and mechanical mates of CAD Software.", "Cognitive", 3, "PLO12"],
    ["ME3601", "Solid Modeling", "4th", "CLO5", "Communicate effectively in both written and oral forms.", "Affective", 2, "PLO10"],
    ["ME2310", "Community Service", "4th", "CLO1", "Discuss various areas of community service (as listed under the topics list) and of relevant ongoing philanthropic activities in the community", "Affective", 2, "PLO6"],
    ["ME2310", "Community Service", "4th", "CLO2", "Demonstrate a sense of responsibility, compassion and empathy towards the community", "Affective", 3, "PLO8"],
    ["ME2310", "Community Service", "4th", "CLO3", "Displays meaningful contribution to have a discernible impact on the community", "Psychomotor", 3, "PLO6"],
    ["ME3501", "Engineering Mathematics – V Numerical Methods", "5th", "CLO1", "Classify the solution of an engineering problem as analytical or numerical", "Cognitive", 2, "PLO1"],
    ["ME3501", "Engineering Mathematics – V Numerical Methods", "5th", "CLO2", "Solve linear and nonlinear equations, differential equations and boundary value problems.", "Cognitive", 3, "PLO2"],
    ["ME3501", "Engineering Mathematics – V Numerical Methods", "5th", "CLO3", "Use computer tools to engineering problems using numerical methods", "Cognitive", 3, "PLO5"],
    ["ME2408", "Signals and Systems", "5th", "CLO1", "Interpret mathematical description and representation of continuous and discrete time signals and systems", "Cognitive", 2, "PLO1"],
    ["ME2408", "Signals and Systems", "5th", "CLO2", "Apply linear systems tools, especially transform analysis and convolution, to  predict  the behavior of linear systems", "Cognitive", 3, "PLO2"],
    ["ME2408", "Signals and Systems", "5th", "CLO3", "Analyze linear systems and gain an appreciation for the importance of linear systems analysis in Mechatronics systems.", "Cognitive", 4, "PLO5"],
    ["ME3508-T", "Artificial Intelligence in Engineering", "5th", "CLO1", "Apply techniques for computer-based representation and manipulation of complex information, knowledge, uncertainty, search problems, optimization, machine learning, neural networks and NLP", "Cognitive", 3, "PLO2"],
    ["ME3508-T", "Artificial Intelligence in Engineering", "5th", "CLO2", "Explain ethical issues pertaining to the use of AI in society", "Cognitive", 2, "PLO8"],
    ["ME3508-L", "Artificial Intelligence in Engineering", "5th", "CLO1", "Develop algorithms to solve problem related to Artificial Intelligence in Engineering.", "Cognitive", 6, "PLO5"],
    ["ME3508-L", "Artificial Intelligence in Engineering", "5th", "CLO2", "Investigate appropriate solution for assigned task.", "Cognitive", 4, "PLO12"],
    ["ME3508-L", "Artificial Intelligence in Engineering", "5th", "CLO3", "Demonstrates the valuing attributes of a life-long learner for project selection and completion.", "Affective", 3, "PLO12"],
    ["ME3509-T", "Microprocessor and Microcontroller Based Systems", "5th", "CLO1", "Explain the fundamentals of hardware and software of the microprocessor and microcontroller and the application of serial interface, timer and interrupt.", "Cognitive", 2, "PLO1"],
    ["ME3509-T", "Microprocessor and Microcontroller Based Systems", "5th", "CLO2", "Apply the capabilities of the 8051 Microcontroller/Arduino to execute a machine code program.", "Cognitive", 3, "PLO2"],
    ["ME3509-T", "Microprocessor and Microcontroller Based Systems", "5th", "CLO3", "Analyze the programming proficiency using the various addressing modes and data transfer instructions.", "Cognitive", 4, "PLO5"],
    ["ME3509-L", "Microprocessor and Microcontroller Based Systems", "5th", "CLO1", "Interpret the concepts of programming and embedded systems used in engineering applications.", "Cognitive", 2, "PLO4"],
    ["ME3509-L", "Microprocessor and Microcontroller Based Systems", "5th", "CLO2", "Construct an assigned team project by integrating mechanical, electronics and embedded control for the given theme.", "Psychomotor", 3, "PLO4"],
    ["ME3509-L", "Microprocessor and Microcontroller Based Systems", "5th", "CLO3", "Communicate effectively in both written and oral forms.", "Affective", 2, "PLO4"],
    ["ME3509-L", "Microprocessor and Microcontroller Based Systems", "5th", "CLO4", "Use different techniques to develop algorithms on microcontrollers software to perform different tasks and note down the readings in the lab manual.", "Cognitive", 3, "PLO5"],
    ["ME3509-L", "Microprocessor and Microcontroller Based Systems", "5th", "CLO5", "Reproduce the Setup for weekly experiments and lab exams", "Psychomotor", 2, "PLO9"],
    ["ME3509-L", "Microprocessor and Microcontroller Based Systems", "5th", "CLO6", "Participate responsibly to complete a task", "Affective", 2, "PLO9"],
    ["ME3508-T", "Instrumentation and Measurements", "5th", "CLO1", "Describe the types and working of instruments and sensors", "Cognitive", 2, "PLO1"],
    ["ME3508-T", "Instrumentation and Measurements", "5th", "CLO2", "Calculate the electrical parameters of instruments and sensors", "Cognitive", 3, "PLO2"],
    ["ME3508-L", "Instrumentation and Measurements", "5th", "CLO1", "Construct the hardware of the assigned project.", "Psychomotor", 3, "PLO3"],
    ["ME3508-L", "Instrumentation and Measurements", "5th", "CLO2", "Analyze a system containing Sensors and Actuators using a top-down approach, initializing from system specifications.", "Cognitive", 4, "PLO3"],
    ["ME3508-L", "Instrumentation and Measurements", "5th", "CLO3", "Communicate effectively in both written and oral forms.", "Affective", 2, "PLO3"],
    ["ME3508-L", "Instrumentation and Measurements", "5th", "CLO4", "Write weekly lab reports", "Cognitive", 3, "PLO9"],
    ["ME3508-L", "Instrumentation and Measurements", "5th", "CLO5", "Reproduce the Setup for weekly experiments and lab exams", "Psychomotor", 2, "PLO9"],
    ["ME3508-L", "Instrumentation and Measurements", "5th", "CLO6", "Participate responsibly to complete a task", "Affective", 2, "PLO9"],
    ["ME3507 -T", "Theory of Machines", "5th", "CLO1", "Explain the fundamentals of mechanics of machines and identify mechanisms and their degrees of freedom.", "Cognitive", 2, "PLO1"],
    ["ME3507 -T", "Theory of Machines", "5th", "CLO2", "Compute kinematic characteristics of mechanisms.", "Cognitive", 3, "PLO2"],
    ["ME3507 -T", "Theory of Machines", "5th", "CLo3", "Analyze a mechanism’s kinetics and balancing requirements to ensure safe operation", "Cognitive", 4, "PLO2"],
    ["ME3507 -L", "Theory of Machines", "5th", "CLO1", "Construct given team project: Fabrication of mechanism to demonstrate its application", "Psychomotor", 3, "PLO3"],
    ["ME3507 -L", "Theory of Machines", "5th", "CLO2", "Compare different mechanism for a given application and justify their selection", "Cognitive", 5, "PLO3"],
    ["ME3507 -L", "Theory of Machines", "5th", "CLO3", "Presents information and findings of the project concisely and logically (project presentation and VIVA)", "Affective", 2, "PLO3"],
    ["ME3507 -L", "Theory of Machines", "5th", "CLO4", "Reproduce the Setup for weekly experiments and lab exams", "Psychomotor", 2, "PLO9"],
    ["ME3507 -L", "Theory of Machines", "5th", "CLO5", "Write weekly lab reports", "Cognitive", 3, "PLO9"],
    ["ME3507 -L", "Theory of Machines", "5th", "CLO6", "Participate responsibly to complete a task", "Affective", 2, "PLO9"],
]];

const normalizedCLO = CLO.map((clo) =>
    clo.map((item) =>
        item.map((value, index) =>
            index === 2 || index === 3 || index === 7
                ? parseInt(String(value).replace(/\D/g, ""), 10)
                : index === 0 ? value.replace(/ -/g, "-") 
                :value
        )
    )
);

console.log(JSON.stringify(normalizedCLO, null, 2));

/*
    const [ courseCode, courseTitle, semester, cloCode, cloDescription, domain, taxonomicLevel, plo ] = clo;
    return {
        courseCode,
        courseTitle,
        semester,
        cloCode,
        cloDescription,
        domain,
        taxonomicLevel,
        plo
    };
*/ 